CREATE DATABASE IF NOT EXISTS quanly_nganhang CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE quanly_nganhang;

-- Bảng Loại Thẻ
CREATE TABLE LOAI_THE (
    MaLoaiThe VARCHAR(20) PRIMARY KEY,
    TenLoai VARCHAR(100) NOT NULL,
    MoTa TEXT,
    TrangThaiXoa TINYINT(1) DEFAULT 0 -- Soft Delete: 0 là bình thường, 1 là đã xóa
);

-- Bảng Khách Hàng
CREATE TABLE KHACH_HANG (
    MaKH VARCHAR(20) PRIMARY KEY,
    TenKH VARCHAR(100) NOT NULL,
    CCCD VARCHAR(20) NOT NULL UNIQUE,
    SDT VARCHAR(20) NOT NULL,
    Email VARCHAR(100),
    DiaChi TEXT,
    NgayDangKy DATETIME DEFAULT CURRENT_TIMESTAMP,
    TrangThaiXoa TINYINT(1) DEFAULT 0
);

-- Bảng Nhân Viên
CREATE TABLE NHAN_VIEN (
    MaNV VARCHAR(20) PRIMARY KEY,
    TenNV VARCHAR(100) NOT NULL,
    ChucVu VARCHAR(50),
    SDT VARCHAR(20),
    TrangThaiXoa TINYINT(1) DEFAULT 0
);

-- Bảng Tài Khoản
CREATE TABLE TAI_KHOAN (
    SoTK VARCHAR(20) PRIMARY KEY,
    MaKH VARCHAR(20),
    SoDu DECIMAL(15, 2) DEFAULT 0,
    NgayMo DATETIME DEFAULT CURRENT_TIMESTAMP,
    TrangThai VARCHAR(20) DEFAULT 'Hoạt động',
    TrangThaiXoa TINYINT(1) DEFAULT 0,
    FOREIGN KEY (MaKH) REFERENCES KHACH_HANG(MaKH) ON DELETE RESTRICT
);

-- Bảng Thẻ
CREATE TABLE THE (
    SoThe VARCHAR(20) PRIMARY KEY,
    SoTK VARCHAR(20),
    MaLoaiThe VARCHAR(20),
    NgayPhatHanh DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayHetHan DATETIME,
    MaPIN VARCHAR(255) NOT NULL,
    TrangThaiXoa TINYINT(1) DEFAULT 0,
    FOREIGN KEY (SoTK) REFERENCES TAI_KHOAN(SoTK) ON DELETE RESTRICT,
    FOREIGN KEY (MaLoaiThe) REFERENCES LOAI_THE(MaLoaiThe) ON DELETE RESTRICT
);

-- Bảng Giao Dịch
CREATE TABLE GIAO_DICH (
    MaGD VARCHAR(50) PRIMARY KEY,
    SoTK VARCHAR(20),
    MaNV VARCHAR(20),
    SoTK_Nhan VARCHAR(20) NULL,
    LoaiGD ENUM('Nạp tiền', 'Rút tiền', 'Chuyển khoản') NOT NULL,
    SoTien DECIMAL(15, 2) NOT NULL,
    ThoiGian DATETIME DEFAULT CURRENT_TIMESTAMP,
    NoiDung TEXT,
    TrangThaiXoa TINYINT(1) DEFAULT 0,
    FOREIGN KEY (SoTK) REFERENCES TAI_KHOAN(SoTK) ON DELETE RESTRICT,
    FOREIGN KEY (MaNV) REFERENCES NHAN_VIEN(MaNV) ON DELETE RESTRICT,
    FOREIGN KEY (SoTK_Nhan) REFERENCES TAI_KHOAN(SoTK) ON DELETE RESTRICT
);
